---
kind: Service
apiVersion: v1
metadata:
  name: base
  labels:
    app: base
spec:
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: base