apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  # labels:
  #   app: web
spec:
  replicas: 6
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.13
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 2
          periodSeconds: 10
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /
            port: 80
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 2
          periodSeconds: 10
        resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
              
