---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        args:
          - /bin/sh
          - -c
          - date; echo Hello from Job!; exit 1;
      restartPolicy: Never
