---
apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 60
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        args:
          - /bin/sh
          - -c
          - while true; do date; echo Hello from Job!; sleep 1; done
      restartPolicy: Never
